### ISSUE TITLE
Switch to Codeship Pro

### ISSUE THREAD

**Issue by teriu** [vital-software/scala-redox#12]
This project is still using Codeship Basic, and needs to be upgraded to the Codeship Pro project type to match our other projects.

**Comment by teriu** [comment]
Fuck it, let's leave this for now unless you see an urgent need to use Docker for this repo. The cost of Codeship Basic is peanuts compared to Pro.

**Comment by mkokho** [comment]
Nope, I don't think we will need Docker for it, it meant to be in a .jar
