### ISSUE TITLE
Interest in Upload Functionality?

### ISSUE THREAD

**Issue by AndrewZurn** [vital-software/scala-redox#16]
Hey there,

Awesome project! We've been working on an implementation recently, and I'm pretty happy I found this nice little client.

Would there be any interest in adding some functionality to this project around performing uploads through the '/upload' Redox endpoint?

Here's the docs on uploading files.
https://developer.redoxengine.com/data-exchange/sending-files-through-redox/

The interface could be something like:
```
def postUpload(file: File): Future[RedoxResponse[UploadResponse]]
```

where `UploadResponse` is
```
case class UploadResponse(URI: URI)
```
or
```
case class UploadResponse(URI: String)
```

If so, I could work on it as apart of our implementation, and submit a PR for this issue. If there isn't interest, or there is some technical reason I can't think of as to why it shouldn't be added, that's perfectly fine as well.

Thanks,
Andrew

**Comment by apatzer** [comment]
Yes! Happy for any contributions to Scala-Redox. Just submit a PR and a
write a test if you can. I’ll publish it out to a Sonatype repo within a
couple of days.

Aaron

**Comment by AndrewZurn** [comment]
Awesome, thanks @apatzer. I'll see what I can do.

It looks like there might indeed be a few technical hurdles as the standalone client doesn't have a good method to send multipart/form-data (https://github.com/playframework/play-ws/issues/126). I've asked around to see if anyone has a good alternative (without re-writing a bunch of Writeables and the code around it). We'll see what I come up with.

Thanks,
Andrew

**Comment by AndrewZurn** [comment]
@apatzer - submitted a PR for this. Let me know how it looks or if you need anything else!
