### ISSUE TITLE
Json support for Auth request

### ISSUE THREAD

**Issue by AndrewZurn** [vital-software/scala-redox#20]
I'm currently running into some issues using the latest version (0.90) making successful requests to the auth endpoint. It seems like the docs state that the auth endpoint should use a content type of json (http://developer.redoxengine.com/data-models/authentication.html).

When attempting to use the current client (from one of my deployed environments) I'm receiving a 401.
```
2017-11-09 02:12:16,769 DEBUG p.s.a.o.a.n.r.NettyRequestSender - Using pooled Channel '[id: 0x02c744e4, L:/100.97.0.15:50900 - R:api.redoxengine.com/52.5.137.221:443]' for 'POST' to 'https://api.redoxengine.com/auth/authenticate'
2017-11-09 02:12:16,769 DEBUG p.s.a.o.a.n.r.NettyRequestSender - Using open Channel [id: 0x02c744e4, L:/100.97.0.15:50900 - R:api.redoxengine.com/52.5.137.221:443] for POST '/auth/authenticate'
2017-11-09 02:12:16,813 DEBUG p.s.a.o.a.n.h.HttpHandler -

Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(freed))
POST /auth/authenticate HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 129
Host: api.redoxengine.com
Accept: */*
User-Agent: AHC/2.0

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 401 Unauthorized
Date: Thu, 09 Nov 2017 02:12:16 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 15
Connection: keep-alive
Cache-Control: private, no-cache, no-store, must-revalidate
Expires: -1
Pragma: no-cache
ETag: W/"f-RGtBbVNe0/VH/NZT3BHUnA"
Vary: Accept-Encoding
set-cookie: sails.sid=s%3AIE-kJgq3ux5NgrGS9Fzbpmfj9ps4c-5v.AINMYtpmcfxbKlEPZx9%2B3mJcnM6yLTuP4yWxbajg9hE; Path=/; Expires=Fri, 10 Nov 2017 02:12:16 GMT; HttpOnly; Secure

2017-11-09 02:12:16,813 DEBUG p.s.a.o.a.n.h.i.Unauthorized401Interceptor - Can't handle 401 as there's no realm
```

Locally, however, I'm seeing this succeed (which is rather odd I would say).
```
2017-11-08 18:01:11,579 DEBUG p.s.a.o.a.n.c.NettyConnectListener - Using new Channel '[id: 0x2a5d2cd3, L:/192.34.100.6:60088 - R:      api.redoxengine.com/34.196.161.187:443]' for 'POST' to '/auth/authenticate'
2017-11-08 18:01:11,581 DEBUG p.s.a.i.n.h.s.SslHandler - [id: 0x2a5d2cd3, L:/192.34.100.6:60088 - R:api.redoxengine.com/34.196.        161.187:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
 2017-11-08 18:01:11,972 DEBUG p.s.a.o.a.n.h.HttpHandler -

 Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf(freed))
 POST /auth/authenticate HTTP/1.1
 Content-Type: application/x-www-form-urlencoded
 Content-Length: 123
 Host: api.redoxengine.com
 Accept: */*
 User-Agent: AHC/2.0
 Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
 HTTP/1.1 200 OK
 Date: Thu, 09 Nov 2017 02:01:12 GMT
 Content-Type: application/json; charset=utf-8
 Content-Length: 145
 Connection: keep-alive
 Cache-Control: private, no-cache, no-store, must-revalidate
 Expires: -1
 Pragma: no-cache
 ETag: W/"91-9IBvEKIjz9qzhA71S6BuhQ"
 Vary: Accept-Encoding
 set-cookie: sails.sid=s%3A7dAQS5v3RjkFlXXa8tApkPPK3eLbSsB-.cpNRmRak01kbcFDaNk5ME4C8AfkoBKgpvzZZLfOPgxk; Path=/; Expires=Fri, 10        Nov 2017 02:01:11 GMT; HttpOnly; Secure
```

When attempting this call using Json I get 200 result (code and logs below).
```
wsClient
    .url("https://api.redoxengine.com/auth/authenticate")
    .withBody(JsObject(Seq("apiKey" -> JsString(RedoxApiKey.trim), "secret" -> JsString(RedoxSecret.trim))))
    .withMethod("POST")
    .execute()
    .foreach { result =>
      logger.info(s"Result of custom auth call: $result")
      logger.info(s"Token: ${result.body}")
    }(scala.concurrent.ExecutionContext.Implicits.global)
```

Logs from deployed env:
```
Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledHeapByteBuf
(freed))
POST /auth/authenticate HTTP/1.1
Content-Type: application/json
Content-Length: 133
Host: api.redoxengine.com
Accept: */*
User-Agent: AHC/2.0

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
Date: Thu, 09 Nov 2017 04:56:26 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 145
Connection: keep-alive
Cache-Control: private, no-cache, no-store, must-revalidate
Expires: -1
Pragma: no-cache
ETag: W/"91-U1mxrXJB8Yk5WGjrQLuCpA"
Vary: Accept-Encoding
set-cookie: sails.sid=s%3AMCSET6YaBiKbzPheTEAbyL2bU7i-vzBp.hefIVxutr2M8m77jKSRT2uIYwWP06vFMC8CWFF%2Bd
KyI; Path=/; Expires=Fri, 10 Nov 2017 04:56:25 GMT; HttpOnly; Secure

2017-11-09 04:56:26,173 DEBUG p.s.a.o.a.n.c.ChannelManager - Adding key: https://api.redoxengine.com:
443 for channel [id: 0xd4812bf8, L:/100.105.128.5:54128 - R:api.redoxengine.com/52.5.137.221:443]
2017-11-09 04:56:26,179 INFO c.d.s.r.j.DeliverReportRunnerFlow - Result of custom auth call: AhcWSResponse(StandaloneAhcWSResponse(200, OK))
2017-11-09 04:56:26,179 INFO c.d.s.r.j.DeliverReportRunnerFlow - Token: {"accessToken":"xxxxxxx","expires":"2017-11-10T04:56:26.131Z","refreshToken":"xxxxxxx"}
```

Is this something you've run into before (the inconsistency in requests made with a content-type of application/x-www-form-urlencoded)? I'm really at wits end as to why a call made with the same client between envs would have different results, and also why using json produces a successful result.

Anywho, being that using json seems to be the documented approach to auth for Redox, would you be open to that change? Kind of an odd request, but potentially worth a discussion (and maybe I'll figure out what's up wrong with my current setup in the process).

I also noticed the `authorize()` method in `RedoxClient` is overridable, but couldn't be used to hook into the other lifecycle events for the class. Might be fun to have it be isolated from the setAuth process, and have the internals handle calling `authorize` and then proceeding to re-set the auth token. (It's late, and I doubt that makes sense, will maybe get back to this when I've gotten a little sleep).

**Comment by apatzer** [comment]
Hey @AndrewZurn I have not seen the behavior your described before, sorry. That said, you make some reasonable suggestions:
 - Change `def authorize` and `def refresh` to use Json rather than form-urlencoded
 - Switch some of the private fields to protected to allow extension through inheritance

I'd prefer the first option, simply because once something is protected, you ideally want to keep things (mostly) backward compatible for anyone building off the Client.

Want to take a stab at changing the auth sequence to Json? Should be relatively straightforward. If not, I may get around to in the coming week.

**Comment by AndrewZurn** [comment]
I could probably get around to completing Option 1 early next week (I currently have it working in my own forked version for my company's project, so it should take long to replicate here).

I might take a stab at decoupling the authorization from the mechanism that stores it as to allow for some easier customization (I'll keep all of the current private members private). 

Thanks!
