### ISSUE TITLE
Make non-critical fields more robust

### ISSUE THREAD

**Issue by pulasthibandara** [vital-software/scala-redox#54]
**What is the purpose of this epic/feature?**
We should't fail at parsing an entire message when a non-critical field like `Contacts.FirstName` fails to parse. The message maybe still useful without these critical fields.

**Detail out your proposed approach**
- [x] Provide a fallback mechanism where we can substitute a valid default for the non-critical field (probably not a `null` value because this can complicate this further)
- ~Add a `@fallback(<value>)` annotation in the `json-annotations` library to handle parsing failures per field.~
- [ ] Maybe log the failure to parse?

**Are there any risks or unknown factors?**
Use of macros can be risky and hard to maintain. However, the final outcome of being able to define a fallback value for each field outweighs the risk.

ex: 
```scala
@json case class DataModel (
	criticalField: String,
	@fallback("default") nonCriticalField: String
)
```

**Comment by apatzer** [comment]
@pulasthibandara Can you use the Json.WithDefaultValues and use the default value somehow instead of creating a new macro?

**Comment by apatzer** [comment]
The other, and perhaps better, alternative, would be to simply make everything that is `nonCritical` an `Option[_]`. Using a fallback is tricky.

If we use a default String for first name, they get an update where we use the fallback, the client code may accidentally believe the name has been updated. It would be better to use an Option instead.

**Comment by pulasthibandara** [comment]
Implemented optional defaults using https://github.com/vital-software/json-annotation/pull/3
