### ISSUE TITLE
Failure to publish is not exiting with the correct error code

### ISSUE THREAD

**Issue by pulasthibandara** [vital-software/scala-redox#66]
**Describe the bug**
The build/publish status is green even when the build has failed. This is because we don't return an error exist code when the publish fails.
https://buildkite.com/vital/scala-redox/builds/145#92b5d496-736e-4b37-8bde-dfd324034cdd/104-342

**Comment by teriu** [comment]
Resolved in https://github.com/vital-software/scala-redox/commit/f82f365ffc47fb6ea13f231ed3a0253e460cdcaf .... (I think)
