### ISSUE TITLE
VisitNumber in VisitQueryResponse should be a number

### ISSUE THREAD

**Issue by mkokho** [vital-software/scala-redox#8]
I asked Redox team, they said that error in the documentation, and that API returning VisitNumber as an integer is a correct behavior.

**Comment by apatzer** [comment]
Cool. Are you on the Redox Slack channel? It's a good one for support as well. http://community.redoxengine.com/

We have a "Vital" subroom that I can invite you to once you're on.

**Comment by mkokho** [comment]
Already fixed in this commit: https://github.com/vital-software/scala-redox/commit/d5aae30889d9e7f903dc9091e685ab57961255b1

They actually fixed the documentation, VisitNumber is a string: http://developer.redoxengine.com/data-models/ClinicalSummary.html#VisitQueryResponse

**Comment by teriu** [comment]
Nice work!
